### ISSUE TITLE
SteamVR tracking negates pre and post swing scores

### ISSUE THREAD

**Issue by NSGolova** [Meivyn/BeatSaberBugs#8]
SteamVR returns inconsistent controller tracking info which leads to the controller moving backward for one frame that stops pre and post swing calculation as this is considered an end of a swing. This makes it impossible to score high accuracy on maps and makes scoring highly susceptive to game performance and type of map.

Steps to reproduce:
- Set your OpenXR runtime to SteamVR
- Run any GPU heavy load (Blender run, video encoding, OBS recording, etc.., up to ~70% GPU load)
- Play any map, but better custom Poodle map as it requires slow consistent swings. Example map:
https://beatleader.xyz/leaderboard/global/3ffd9x91/1

Investigation results:
- Doesn't reproduce on OpenVR API (1.29.1 or by modding it back)
- Doesn't reproduce on Oculus implementation of OpenXR
- There are frames with (0, 0, 0) tracking, getting rid of them doesn't fix the issue.
- Using input actions as events(`unityXrController.positionAction.performed +=`) instead of polling on Update doesn't fix the issue.
- Updating or downgrading OpenXR doesn't fix the issue.
- Updating or downgrading SteamVR doesn't fix the issue.
- There is no obvious timing pattern (ie "bad frames" having too big or too small time delta)
- There is no obvious action pattern (ie cutting note or moving head)
- Investigation on sample Unity projects was inconclusive, I had "zero frame" issues with 2019.3 Unity sample but it failed to reproduce on @Meivyn 's setup. 2022.3 Unity sample that used Actions had no issues for me, but without replicating cut logic or replay recording it's hard to tell for sure.

Recordings (The pink area is a single frame):
Normal gameplay (no GPU load, 72fps)
<img width="600" alt="image" src="https://github.com/user-attachments/assets/cdffda6e-ac55-41d4-9194-b7fbeb225f97">
High GPU load, "zero frame" issue
<img width="600" alt="image" src="https://github.com/user-attachments/assets/698008f6-b77d-4bcd-b01f-55150e8bcaec">
High GPU load, "moving backward" issue
<img width="600" alt="image" src="https://github.com/user-attachments/assets/158b3a6e-7ad3-4a2c-a32d-c82abc272ac0">

Replay of gameplay on low framerate:
https://replay.beatleader.xyz/?link=https://api.beatleader.xyz/otherreplays/76561198059961776-1731791011-ExpertPlus-Standard-522F776A287C9CEDCF321D1384F8BDB2113EA7D0.bsor
_enable "Show hitboxes" in the web player settings for "frame-by-frame" playback_

**Comment by nnuber** [comment]
Some issues related to this have been addressed in the SteamVR 2.10.2 Beta. Can you retest using that version?

**Comment by GalaxyMaster2** [comment]
From my testing the jitter issue seems to be completely gone. I previously traced back the issue all the way to 1.16.1, with 1.15.19 being the last version without the issue. 2.10.2 seems to behave as well as 1.15.19 did.

I was never able to reproduce the "zero frames" issue though, so I cannot comment on the status of that.

**Comment by Meivyn** [comment]
I can confirm that this update has resolved all the issues we observed. Backward movements have returned to normal (still present, but now comparable to Oculus), and the zero-frame issue appears to be completely fixed.

I’ll wait for this to reach the stable release before closing the issue.

A huge thank you for addressing this! It was a significant problem for the competitive community. I have no idea how a Valve employee ended up on this repo, but I’m very grateful that they did.

**Comment by Galicjanin** [comment]
I noticed great reduction of saber jitter on my test setup. Still not as good as Oculus OpenXR, but my setup is extremally prone to this bug to occur. Zero-frames are completely absent in 2.10.2
SteamVR release 2.9 as OpenXR runtime: https://replay.beatleader.com/?scoreId=22262877
SteamVR beta 2.10.2 as OpenXR runtime: https://replay.beatleader.com/?scoreId=22576833
Oculus as OpenXR runtime: https://replay.beatleader.xyz/?scoreId=19912727

You can use this replay analyzer for all three replays to get jitter and zero-frames timestamps: https://slinkstr.com/beat-saber/jitter-detector/

**Comment by Meivyn** [comment]
@Galicjanin Could you send a replay on the 1.15.12 beta too? So far I didn't see such a big difference between SteamVR and Oculus. Also, please make them back-to-back, on the same day. Comparing old replays is unreliable.

**Comment by Galicjanin** [comment]
Sorry, it is hard for me to test on 1.15.12 beta, as I get distorted view in Quest 3 HMD when running modded BS (like bigger render fov squished to narrower HMD fov). I believe this was my attempt to play on 1.15.12 beta. I barely could hit blocks with this distorted view, but swings seems to be fine (tried slinkstr tool to find jittered swings and most found are false positives): https://replay.beatleader.com/?scoreId=21974567
I will try to make comparison on same day in the weekend. Ideal would be to have same map for all gameplays, but scores are not sent when high score is not beaten.

**Comment by Meivyn** [comment]
You can turn on public attempts on your BL profile on the website. Otherwise, could still do `https://replay.beatleader.com?link=<LINK_TO_REPLAY_FILE>` after uploading the replay file somewhere to get a direct link.

**Comment by Galicjanin** [comment]
@Meivyn BeatLeader don't upload recording unless it is highest score. Otherwise it uploads only a score.
I can't see replay button on attempts that don't beat best score:
![Image](https://github.com/user-attachments/assets/4eafc74d-b67d-400d-b4c8-43cb0171e9d2)


EDIT: I can try to play map in order of expected results and get highest score each time this way. 1.15 (expected score 60% due to distorted view), then 2.9 (85% due to common swing bug cutting 50% of scores and zero-frames), 2.10 (~95% rare swing bug cutting ~5% of cut scores), Oculus OpenXR (~96%)

**Comment by Galicjanin** [comment]
SteamVR 1.15 https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/22597460.bsor

SteamVR 2.9 https://github.com/Galicjanin/files/raw/refs/heads/main/76561198025868413-Cola%20Song-Hard-Standard-92952F8E81D4B9E8AFCA468FAABB117FD0D663E2-1743777011.bsor
(don't have proper file storage to provide it as link to replay and I couldn't beat 1.15 score, so it is not uploaded to BeatLeader servers. You can rewatch it via going to https://replay.beatleader.com/ and selecting bsor file from local drive)

SteamVR 2.10.2 https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/22597682.bsor

Oculus as OpenXR: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/22597825.bsor

Game is the same for all gameplays. 1.39.1 with few mods to cause fps drops.
Also I've just set my attempts public.

**Comment by HypersonicSharkz** [comment]
I am not seeing any improvement with SteamVR 2.10.2 on Beat Saber 1.39.1. It happens at least once every single map, and is especially noticeable on poodle maps as it resets the swing for the whole poodle. The stutters are also not noticeable at all when playing making it seem like it just resets the swing. 

I have a replay from before 2.10.2 showing the issue: https://replay.beatleader.xyz/?scoreId=19267366&cpx=0.000&cpy=1.750&cpz=2.000&crx=0.000&cry=0.000&time=172566&speed=6

And same issue on 2.10.2: https://youtu.be/H5RvzVspcVs

This has NEVER happened on Beat Saber 1.29.1, no matter how much I force my game to stutter. It simply does not do the weird swing reset movement when it stutters.

**Comment by Meivyn** [comment]
@Galicjanin I see that it's clearly worse on SteamVR, and that it *drastically* improved with the Beta, but you still get *a lot* of jitters on Oculus. Could you make a replay on 1.29.1 or less so I can compare it with OpenVR too?

@HypersonicSharkz 

> This has NEVER happened on Beat Saber 1.29.1, no matter how much I force my game to stutter. It simply does not do the weird swing reset movement when it stutters.

This is simply false, as demonstrated by this replay made on game version 1.25.0: <https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-04C76A54C4649B04EE8A47B6C978BF30A6EFABDA.bsor&time=189472&speed=2>, and I'm sure I would be able to find more when digging. For reference, here's a list of replays where you did lose score because of underswings caused by some form of jitters:

```
https://cdn.replays.beatleader.com/12879275-76561198089913211-ExpertPlus-Standard-BDEBD0E4B5DF0A8AD592E04D294C8E3DF4248667.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/9653025-76561198089913211-ExpertPlus-Standard-ABE3086C23BA2C8F7C92620F8B612C576768E295.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-04ECA67F7DF4E277D188FA5D7B939F9146753160.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-5711009-Expert-Standard-615E2F6965DC2AEF8A29E2940904542BE05B11A7.bsor 1.28.0_4124315132
https://cdn.replays.beatleader.com/76561198089913211-Hard-Standard-4E19C93FF2D7E086536AEAB2F551C2E184160640.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-BD9C8E4F55690983C72552FBED1338AE77D2A6E8.bsor 1.23.0
https://cdn.replays.beatleader.com/17655214-76561198089913211-ExpertPlus-Standard-522E3F1267DDD644F3587004064BED83ADCC9833.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-58EC0C23FE7884DB894F874A9E6C41CD5FA0E920.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-04C76A54C4649B04EE8A47B6C978BF30A6EFABDA.bsor 1.25.0
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-E24FB7D5EA14E7DD155AAF59BE80E9DC5958F876.bsor 1.23.0
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-071BA4FD4F08F74ABBA5FFBE3315E5006284909F.bsor 1.24.1
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-2E4614DE850731444559C6FBEEDDF789FAC2784B.bsor 1.28.0_4124315132
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-D7D24C7AF3085D8E2C0B16FDE9150DDF02895AD2.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-1D4265129CF078090CB43CE2CB4D927E15CF9863.bsor 1.25.0
https://cdn.replays.beatleader.com/17052452-76561198089913211-Expert-Standard-B14314329BE9676417448404A59619E3CE9EBE48.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-85DB70578FC08ECDA04DD8F51F60FD5ECB050546.bsor 1.25.0
https://cdn.replays.beatleader.com/22179640-76561198089913211-Expert-Standard-2A4491C3BBB920C5A620417B80622272222CC228.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-C7FE193DC891DC3C3012CC6482AB9E3FB5AB390D.bsor 1.27.0_3631158313
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-23015A4E5087A298C723754C64DFD36A668386AE.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-2F2C1CC092DC4C75EBB27F2252651010D15C25D0.bsor 1.27.0_3631158313
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-77EAA44A91670C77791289279D645BC144D9B771.bsor 1.23.0
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-2BB2289C50607B01BA13EF6274BC4916CFE4E940.bsor 1.25.0
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-328277FF5FB15A1F3B7CDE7277C2190904CEA824.bsor 1.23.0
https://cdn.replays.beatleader.com/21023273-76561198089913211-ExpertPlus-Standard-F77728BB6BFFD097E6E4C10CCBE72B5E8A51FF82.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-5FC930DD535F282D1C8A0ABD1D1407B10A5ABF5C.bsor 1.24.1
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-79D9DACEC0607F45E868A3F49B0795B3341EFFB2.bsor 1.25.0
https://cdn.replays.beatleader.com/19245968-76561198089913211-Expert-Standard-BDF85D5D575A992139EFF968A8348B3E6F03EEFE.bsor 1.38.0_11020369061
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-7719B8DE597CB1BFDFD6048E5FC51656DD5219EE.bsor 1.27.0_3631158313
https://cdn.replays.beatleader.com/22368645-76561198089913211-Expert-Standard-187BEA15DE6BD730123917F889C2690A1500433C.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/12282070-76561198089913211-ExpertPlus-Standard-3E6C073B44FEAA26D06699D0EE7F24524E62AEF5.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/21023490-76561198089913211-ExpertPlus-Standard-762B7BF1C06DBCC7AAB23D955A553E5420FBA6E5.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/19245834-76561198089913211-Hard-Standard-32F8CE033B4AA48798A65A5E5B4DA45B6D7A38F7.bsor 1.38.0_11020369061
https://cdn.replays.beatleader.com/18158429-76561198089913211-ExpertPlus-Standard-FAEC3B7EF37931477DD664FCA5E8EB1CC607CEB5.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-75B10748149340DEA74FF1870B2A59F609ACE7F5.bsor 1.27.0_3631158313
https://cdn.replays.beatleader.com/76561198089913211-Normal-Standard-7BDD78A1787E0FD59A24466D700E1683B1CF5DE4.bsor 1.25.0
https://cdn.replays.beatleader.com/17673174-76561198089913211-Expert-Standard-B758BA486DDD190D87EF5C87525FB1286E36E52B.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-26933342740E324FFEEEB1FF53F5231E5CEA3D95.bsor 1.24.1
https://cdn.replays.beatleader.com/76561198089913211-Expert-Standard-3631D5E2D465E42FA299ABDE61D432A3029CD192.bsor 1.23.0
https://cdn.replays.beatleader.com/14452296-76561198089913211-Expert-Standard-AA0A150D83B499C8BECC3BEDA1C17AC4D9D97D40.bsor 1.29.1_4575554838
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-93219A28885AFC6665B7289631420FDE9A2ECBFF.bsor 1.24.1
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-9E3CD9B0C5559167E31E6894C14E391AEA937991.bsor 1.25.0
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-5909C4CC3F242632BF4C826305732489F8C54F9B.bsor 1.24.1
https://cdn.replays.beatleader.com/76561198089913211-ExpertPlus-Standard-914EDCFA17A8D7B1573F7FE8EB1B504CC7E47806.bsor 1.24.1
```

From what I can see of your replays analysis, your left controller clearly has tracking issues overall. Every single of the underwings it could find is happening with your left hand. And this *only* includes replays where you lost score, it would be worse otherwise.

It'll be helpful if you could provide a replay on 1.29.1 and 1.39.1 with heavy GPU/CPU tasks in the background. Make it barely playable basically, and play like that. Then send replays for analysis.

**Comment by Galicjanin** [comment]
@Meivyn https://github.com/Galicjanin/files/raw/refs/heads/main/76561198025868413-Cola%20Song-Hard-Standard-92952F8E81D4B9E8AFCA468FAABB117FD0D663E2-1744053458.bsor
EDIT: Sorry, gameplay above was with partricles bumped up by about 50% compared to 1.39.1 gameplays.

Here is 1.29.1 gameplay with same reesaber settings as on 1.39.1: https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/22678639-76561198025868413-Hard-Standard-92952F8E81D4B9E8AFCA468FAABB117FD0D663E2.bsor

**Comment by HypersonicSharkz** [comment]
@Meivyn 

This was played while using 100% of all my cpu cores. Tons of visible stutters ingame, but didn't notice any underswing due to it
https://replay.beatleader.com/?scoreId=22677621

This was played while using 100% cpu and also very high GPU util. Had around 50fps I would say, while also getting some nasty spikes. But still did not notice much of underswing due to it.
https://replay.beatleader.com/?scoreId=22677975

**Comment by Meivyn** [comment]
@Galicjanin Obviously your setup doesn't like OpenXR, you still get much more jitters on Oculus than what you get on OpenVR, but a lot less than what you get on SteamVR OpenXR. So far you're the only one I saw with such a difference between all runtimes. 

@HypersonicSharkz Could you play the same map rather than different ones, on both versions? Have to see if there's a significant difference between both when having framerate issues.

**Comment by Galicjanin** [comment]
@Meivyn keep in mind my setup is worst case scenario. In reesaber MainConfig i set "particlesCountMultiplier": 10.0 for both sabers and on one saber addictionaly "ParticlesCount": 5120 instead of "ParticlesCount": 512. As far as I know changes in refresh rate caused by this setup are worse than constant cpu/gpu load.

**Comment by HypersonicSharkz** [comment]
@Meivyn I have made a more thorough test for both versions of SteamVR and Beat Saber
https://github.com/HypersonicSharkz/replays
I did not test 1.29.1 on SteamVR 2.9.6. However I can do so if needed.

Edit:
I am on a HTC Vive with Index Controllers

**Comment by DarkHornet17** [comment]
So i am wondering; in the instances where Jitters still occur, what is the headset being used? I don't know if anyone has acknowledged or otherwise dis-proven exactly what hardware the issue persists on (the lack of knowledge of a centralized thread doesn't help, I am trying to stay up to date with developments)

**Comment by slinkstr** [comment]
I've saved every local replay for the last couple years, so I have a much larger dataset on my machine than what I can pull from BeatLeader. I've gone through and scanned 2.7k of my own replays with the jitter detector I made ([website](https://slinkstr.com/beat-saber/jitter-detector/), [CLI](https://github.com/slinkstr/BeatLeaderScoreScanner/)). It is not 100% accurate, but I've restricted replay selection to compensate. I filtered out any replays with a score below 95% to select for easier songs with controlled swings, since hard swings tend to cause tracking inaccuracies and rubber banding on all versions.

I've been using the 2.10.2 SteamVR beta with Beat Saber 1.39.1 since it was made available on 2025-04-02. Looking at the number of jitters per replay, it has made an obvious improvement over the non-beta branch, but there is still a discrepancy between 1.39.1 and 1.29.1. See images below for a summary - these replays were gathered over the course of several months, switching back and forth between 1.39.1 and 1.29.1. 

I've manually verified a handful of replays from each group, and it appears the occasional jitters shown on my 1.29.1 chart represent the error rate of the data in general. Examples of what was detected: [1](https://replay.beatleader.com/?link=https://files.catbox.moe/akuhe3.bsor&speed=2&time=164400), [2](https://replay.beatleader.com/?link=https://files.catbox.moe/h74v3b.bsor&speed=2&time=124348), [3](https://replay.beatleader.com/?link=https://files.catbox.moe/x45fos.bsor&speed=2&time=40498), [4](https://replay.beatleader.com/?link=https://files.catbox.moe/j2fya5.bsor&speed=2&time=103619), [5](https://replay.beatleader.com/?link=https://files.catbox.moe/4qm4s3.bsor&speed=2&time=10829)

I did a few tests where I artificially caused lag with Kombustor's CPU burner (set to 29 of 32 threads), and these reflect my findings of 1.29.1 having no issues while 1.39.1 with 2.10.2 SteamVR suffers somewhat, but again: much better than 1.39.1 on the current stable SteamVR, which was an order of magnitude worse. Replay files: [1.29.1](https://files.catbox.moe/p7s601.bsor), [1.39.1 stable](https://files.catbox.moe/8tinuc.bsor), [1.39.1 beta](https://files.catbox.moe/43cvpz.bsor)

As for @HypersonicSharkz replays showing jitter on 1.29.1, it looks similar but I'm not convinced it's the same issue. Every instance of jitter I've checked in my own replays affects both hands simultaneously. If it is affecting their left hand only, I find that strange. I also notice the timestamp linked is in the middle of a quick burst...

@DarkHornet17
PC specs: https://pcpartpicker.com/list/XLYvmC
Headset: Valve Index with Index controllers

1.39.1 with beta SteamVR:
![Image](https://github.com/user-attachments/assets/66ef5bc7-bfdf-446b-b17a-5f554aa78398)

1.39.1 with stable SteamVR:
![Image](https://github.com/user-attachments/assets/01d9a151-0f9d-4270-aa2a-04171e8b74e5)

1.29.1:
![Image](https://github.com/user-attachments/assets/5e93a000-7f31-4045-874b-217996269e80)

**Comment by firebingo** [comment]
I seem to be running into a odd case where steamvr 2.10 is making the jitter issue worse for me. I've been testing on game version 1.40.4 and steamvr 2.10.4 produces more jitter for me than 2.9.6, and beta 2.11.1 seems to make the problem even worse. I don't get any jitters running on game version 1.29.1. The only mods I have installed on 1.40.4 are the default mods from bsmanager, beat leader, and easy offset.
Here is the outputs from the jitter detector for the replays.
```
.\BeatLeaderScoreScanner-win-x64.exe --require-score-loss --allow-file "I:\1_29_1_2_10_4.bsor"
2025-05-17 | Index, OpenVR, 1.29.1_4575554838, 0.9.20 | 93.97% | Lost 1000 points (0.51%), fullswing acc: 94.48% | 0 jitters (0.00/min) | 0 origin resets (0.00/min) | Outer Wilds
.\BeatLeaderScoreScanner-win-x64.exe --require-score-loss --allow-file "I:\1_40_4_2_9_6.bsor"
2025-05-17 | Valve Index, OpenXR, 1.40.4_5283, 0.9.33 | 93.04% | Lost 2048 points (1.05%), fullswing acc: 94.09% | 9 jitters (6.75/min) | 0 origin resets (0.00/min) | Outer Wilds
.\BeatLeaderScoreScanner-win-x64.exe --require-score-loss --allow-file "I:\1_40_4_2_10_4.bsor"
2025-05-17 | Valve Index, OpenXR, 1.40.4_5283, 0.9.33 | 92.00% | Lost 3858 points (1.98%), fullswing acc: 93.98% | 12 jitters (9.00/min) | 0 origin resets (0.00/min) | Outer Wilds
.\BeatLeaderScoreScanner-win-x64.exe --require-score-loss --allow-file "I:\1_40_4_2_11_1.bsor"
2025-05-17 | Valve Index, OpenXR, 1.40.4_5283, 0.9.33 | 91.47% | Lost 4120 points (2.11%), fullswing acc: 93.59% | 13 jitters (9.75/min) | 0 origin resets (0.00/min) | Outer Wilds
```
And here are the replays [1.29.1-2.10.4](https://files.catbox.moe/h90r9p.bsor), [1.40.4-2.9.6](https://files.catbox.moe/4nr4qs.bsor), [1.40.4-2.10.4](https://files.catbox.moe/e5blnh.bsor), [1.40.4-2.11.1](https://files.catbox.moe/z6ebis.bsor)

I'm playing on a Valve Index with the Index controllers.
[System spec](https://files.catbox.moe/4grbni.png)
Is there any further information I could provide or more testing to help indicate why the steamvr version that is improving the issue for other people seems to make it worse for me?

**Comment by slinkstr** [comment]
I previously mentioned that 1.15.12 fixes the issue, but I appear to have been mistaken. I re-tested latest beta SteamVR (2.12.2) vs the old beta SteamVR (1.15.12) and there seems to be no difference now. Beat Saber 1.40.5 has numerous jitters that drop my score on either version.

SteamVR's performance graph shows a purple line every few seconds. If a jitter occurs it is always during these moments. I included videos with the performance graph and MSI Afterburner's FPS overlay visible. Unfortunately I only have one other recording with the graph visible from a few months back, but there are no purple lines and no jitter (SteamVR 1.15.12, Beat Saber 1.39.1).

I included jitter detector count as a reference, but I also looked at the underswings for some of these replays and there are more it missed, like [this](https://replay.beatleader.com/?link=https://files.catbox.moe/4vt9pt.bsor&time=44193&speed=5) and [this](https://replay.beatleader.com/?link=https://files.catbox.moe/oo291f.bsor&time=51536&speed=5).

I also tested 1.29.1 on latest as a sanity check. While the jitter counts are almost 0, the few that are detected have all the same characteristics as on other versions, rather than just a Tracking Moment™️ false positive like from previous batches. Unsure if that is due to a new problem or to me not checking previous replays more thoroughly.

## Latest SteamVR, 1.40.5
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/4vt9pt.bsor>), [replay file](<https://files.catbox.moe/4vt9pt.bsor>), [video](<https://youtu.be/3dUvuHJEscI>), tool reports 2.49/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/oo291f.bsor>), [replay file](<https://files.catbox.moe/oo291f.bsor>), [video](<https://youtu.be/KrrhZkgHp6k>), tool reports 4.57/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/ye5c9w.bsor>), [replay file](<https://files.catbox.moe/ye5c9w.bsor>), [video](<https://youtu.be/Wez_t78CAwM>), tool reports 3.81/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/t54hq4.bsor>), [replay file](<https://files.catbox.moe/t54hq4.bsor>), [video](<https://youtu.be/rhD5Gxnz4zQ>), tool reports 3.34/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/3c3iv7.bsor>), [replay file](<https://files.catbox.moe/3c3iv7.bsor>), [video](<https://youtu.be/LbKirZhkU6o>), tool reports 7.67/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/wwknyb.bsor>), [replay file](<https://files.catbox.moe/wwknyb.bsor>), [video](<https://youtu.be/EYoE2Tb4NjI>), tool reports 4.95/min

## Old SteamVR, 1.40.5
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/oaklir.bsor>), [replay file](<https://files.catbox.moe/oaklir.bsor>), [video](<https://youtu.be/EvPIQV062to>), tool reports 6.9/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/v5tpkj.bsor>), [replay file](<https://files.catbox.moe/v5tpkj.bsor>), [video](<https://youtu.be/JdFVjWfEY6k>), tool reports 3.23/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/3o3cio.bsor>), [replay file](<https://files.catbox.moe/3o3cio.bsor>), [video](<https://youtu.be/nhjEDpQi2lk>), tool reports 6.72/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/1wehz7.bsor>), [replay file](<https://files.catbox.moe/1wehz7.bsor>), [video](<https://youtu.be/iFqdCRw-_Po>), tool reports 3.87/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/m5r330.bsor>), [replay file](<https://files.catbox.moe/m5r330.bsor>), [video](<https://youtu.be/CdpIXt2hfbI>), tool reports 5.5/min

## Latest SteamVR, 1.29.1
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/741yer.bsor>), [replay file](<https://files.catbox.moe/741yer.bsor>), [video](<https://youtu.be/deqVzuiY9x8>), tool reports 1.2/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/8bvxg6.bsor>), [replay file](<https://files.catbox.moe/8bvxg6.bsor>), [video](<https://youtu.be/DHige118-KA>), tool reports 0/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/aromc7.bsor>), [replay file](<https://files.catbox.moe/aromc7.bsor>), [video](<https://youtu.be/KEFz7iWnqTQ>), tool reports 0.56/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/r15ozl.bsor>), [replay file](<https://files.catbox.moe/r15ozl.bsor>), [video](<https://youtu.be/gcT34yyMQ6U>), tool reports 0.37/min
[replay](<https://replay.beatleader.com/?link=https://files.catbox.moe/bneupg.bsor>), [replay file](<https://files.catbox.moe/bneupg.bsor>), [video](<https://youtu.be/EjyZMEVqSYE>), tool reports 0/min

**Comment by slinkstr** [comment]
Small update with recent findings:
* Rolling back NVIDIA drivers to 560.94 (2024-08-14) resolved the constant purple lines in SteamVR. I was previously on 576.80 (2025-06-12).
* After resolving that, re-testing with a CPU stress test running did not cause any extra jitters (aside from 2 moments where a purple line appeared, 3 minute song)

Seems like SteamVR 2.10.2 resolved the issue when the game drops frames, but this is another cause with the same symptoms? Jitters from this cause *did* also occur on Beat Saber 1.29.1, but significantly less than on later versions.

Edit 2025-08-20: NVIDIA drivers newer than 580.88 (2025-07-31) also solve SteamVR stuttering according to community findings.

**Comment by Umbranoxio** [comment]
Figured I'd post this in here https://github.com/Umbranoxio/open-xr-underswing-fix
The fix here is unconfirmed as of writing this but either way, contains some useful research

**Comment by Galicjanin** [comment]
> Figured I'd post this in here https://github.com/Umbranoxio/open-xr-underswing-fix The fix here is unconfirmed as of writing this but either way, contains some useful research

Gave it a chance (on 1.40.8) and seems like it helps. I definitely feel difference. Will do some analyze of recordings later, but I feel confident enough to already say: Thank you for fixing the game for me! <3


EDIT: Reviewed replays and can confirm that I can't find a jitter causing swing reset from several today's playthroughs made on extreme conditions from 5 tries. On other tries before installing this mod I can easily find such situations even on much better conditions.

**Comment by Umbranoxio** [comment]
@Galicjanin Appreciate you going through the effort of giving this a try, I'm glad to hear it went well for you!

If there's any replays / data you can share at some point that'd be awesome.

**Comment by Galicjanin** [comment]
@Umbranoxio I will do some proper testings this week. Yesterday's tests you can check here:
https://beatleader.com/u/irbisthecat/attempts
I analyzed replays using slinkstr's tool and found only false positives for swing bug.
This setup is extremally prone for bug to happen, as my fps was jumping like crazy thanks to setting tons of particles on saber swings.
Today I might uninstall your mod and try same maps without it on 1.40.8. Later this week will do same maps on 1.29.1

**Comment by Meivyn** [comment]
You were the only one who could reproduce the problem consistently using the Oculus OpenXR runtime, so I find these results pretty conclusive on their own.

**Comment by Galicjanin** [comment]
@Umbranoxio Catch some data. I don't call it an effort. I call it enjoyment of seeing bug being found and adressed by someone, even if it needs a mod to fix! Pardon my lack of knowledge/understanding, but since core reason was found, who can fix it, so it doesn't need a mod? Steam devs, Unity devs or BeatSaber devs? Who is to chase for improvements, and can bug also occur in other games, but BS was most noticeable due to its scoring mechanics?

Replayed all songs I played yesterday. Only change made was disabling mod from Umbranox.
During gameplay on every single map I was noticing unexplainable score losses due to "big underswings" (I have scores display blue bars depending on how much I underswing pre/post swing, so I can easily notice occurances and distinguish if it was small or big underswing)

modded: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/33547130.bsor
mod removed: https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575471-76561198025868413-Hard-Standard-666E016F17BCB750E741A5913C573A5AB2F53078.bsor
modded: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/33546999.bsor
mod removed: https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575548-76561198025868413-Hard-Standard-E531247F99CB90679F7AD64ED0BE1323D976844A.bsor
modded: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/33546930.bsor
mod removed: https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575596-76561198025868413-Expert-Standard-070007FF180423AA0ABF3F2BA5584B0846788EE8.bsor
modded: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/33546840.bsor
mod removed: https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575657-76561198025868413-Expert-Standard-07AE52FDB72C41DD04E12D7E51FD27265F388704.bsor
modded: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/33546793.bsor
mod removed: https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575706-76561198025868413-Hard-Standard-E4B1E54D1B64F6E3F3247BA36E95EC1327EB033B.bsor
modded: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785164881-Hard-Standard-B7D9D652C3A1C4FE37BE506379B958B0056565EA.bsor
mod removed: https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785272587-Hard-Standard-B7D9D652C3A1C4FE37BE506379B958B0056565EA.bsor

Now tool from Slinkstr analyze.
Easily I can find the bug by checking underswings:
https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575471-76561198025868413-Hard-Standard-666E016F17BCB750E741A5913C573A5AB2F53078.bsor&speed=2&time=59947
https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575471-76561198025868413-Hard-Standard-666E016F17BCB750E741A5913C573A5AB2F53078.bsor&speed=2&time=78888

https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575548-76561198025868413-Hard-Standard-E531247F99CB90679F7AD64ED0BE1323D976844A.bsor&speed=2&time=21493

This one is cool/nasty. Like 4 times bug occured during one swing
https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575548-76561198025868413-Hard-Standard-E531247F99CB90679F7AD64ED0BE1323D976844A.bsor&time=110555&speed=2

https://replay.beatleader.com/?link=https://cdn.replays.beatleader.com/33575706-76561198025868413-Hard-Standard-E4B1E54D1B64F6E3F3247BA36E95EC1327EB033B.bsor&speed=2&time=114790

I can find underswings caused by bug only after mod removal

**Comment by Umbranoxio** [comment]
@Galicjanin amazing data, thank you so much for the confirmation! Awesome to see. Just a heads up you'll notice a 0.2.0 version has been released. As you are not using steamvr this version will operate largely in the same way so don't expect to see results that are any different.

**Comment by Galicjanin** [comment]
@Umbranoxio Oh, I am using SteamVR openXR runtime:
<img width="765" height="501" alt="Image" src="https://github.com/user-attachments/assets/2fb2c13b-e954-401d-936f-5db869730773" />

My full path from Quest 3 HMD to BeatSaber is: HMD -> Oculus Link through the usb3 cable (120hz, async spacewarp disabled for other reasons, but it also makes game more prone to show the bug) -> SteamVR started from oculus -> BeatSaber started from SteamVR with SteamVR openXR runtime set. I will do tests for new version 0.2.0 when I find some time.
I can switch also to Oculus openXR runtime for testing if you want me to try also this with and without your mod.

**Comment by Galicjanin** [comment]
@Umbranoxio 0.2.0 is huge regression compared to 0.1.0.
EDIT: Sent you an email so we can do some more testing and send logs/builds via other forms of communication.

[INFO @ 22:40:46 | OpenXR Underswing Fix] patched SteamVR/OpenXR at +0x24FB0 (120hz)
[INFO @ 22:40:47 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:40:50 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:40:52 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:40:54 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:40:55 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:41:02 | OpenXR Underswing Fix] updated to 30hz
[INFO @ 22:41:03 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:41:06 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:41:16 | OpenXR Underswing Fix] updated to 40hz
[INFO @ 22:41:17 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:41:19 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:41:20 | OpenXR Underswing Fix] updated to 120hz
(...)
[INFO @ 22:42:48 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:42:49 | OpenXR Underswing Fix] updated to 40hz
[INFO @ 22:42:50 | OpenXR Underswing Fix] updated to 15hz
[INFO @ 22:42:51 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:42:52 | OpenXR Underswing Fix] updated to 40hz
[INFO @ 22:42:53 | OpenXR Underswing Fix] updated to 60hz
[INFO @ 22:42:54 | OpenXR Underswing Fix] updated to 30hz
[INFO @ 22:42:55 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:42:56 | OpenXR Underswing Fix] updated to 40hz
[INFO @ 22:42:57 | OpenXR Underswing Fix] updated to 120hz
[INFO @ 22:42:58 | OpenXR Underswing Fix] updated to 120hz

0.1.0 had only [INFO @ 17:15:23 | OpenXR Underswing Fix] patched SteamVR/OpenXR at +0x24FCB

Replays:
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785445140-Hard-Standard-B7D9D652C3A1C4FE37BE506379B958B0056565EA.bsor
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444916-Hard-Standard-E4B1E54D1B64F6E3F3247BA36E95EC1327EB033B.bsor
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444789-Expert-Standard-07AE52FDB72C41DD04E12D7E51FD27265F388704.bsor
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444596-Expert-Standard-070007FF180423AA0ABF3F2BA5584B0846788EE8.bsor
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444467-Hard-Standard-E531247F99CB90679F7AD64ED0BE1323D976844A.bsor
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444276-Hard-Standard-666E016F17BCB750E741A5913C573A5AB2F53078.bsor

Examples:
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444276-Hard-Standard-666E016F17BCB750E741A5913C573A5AB2F53078.bsor&speed=2&time=100493
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444276-Hard-Standard-666E016F17BCB750E741A5913C573A5AB2F53078.bsor&speed=2&time=81464
https://replay.beatleader.com/?link=https://api.beatleader.com/otherreplays/76561198025868413-1785444789-Expert-Standard-07AE52FDB72C41DD04E12D7E51FD27265F388704.bsor&speed=2&time=161654
